### ISSUE TITLE
最近老是报这样的错误...goroutine 29455 [IO wait]

### ISSUE THREAD

**Issue by TruthHun** [aliyun/aliyun-oss-go-sdk#250]
```
goroutine 28890 [select]:
net/http.(*persistConn).writeLoop(0xc0002c7680)
	c:/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	c:/go/src/net/http/transport.go:1648 +0xc7b

goroutine 29455 [IO wait]:
internal/poll.runtime_pollWait(0x7fc18476b320, 0x72, 0xffffffffffffffff)
	c:/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc008647218, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
	c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	c:/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc008647200, 0xc00e510000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	c:/go/src/internal/poll/fd_unix.go:169 +0x19b
os.(*File).read(...)
	c:/go/src/os/file_unix.go:263
os.(*File).Read(0xc00e7476d8, 0xc00e510000, 0x8000, 0x8000, 0x0, 0x10000c000036f00, 0x0)
	c:/go/src/os/file.go:116 +0x71
io.copyBuffer(0xec4300, 0xc01444ff40, 0xec41e0, 0xc00e7476d8, 0xc00e510000, 0x8000, 0x8000, 0x0, 0xc00886a540, 0xc000036f50)
	c:/go/src/io/io.go:405 +0x122
io.Copy(...)
	c:/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x1, 0x0)
	c:/go/src/os/exec/exec.go:310 +0x63
os/exec.(*Cmd).Start.func1(0xc0086451e0, 0xc006173800)
	c:/go/src/os/exec/exec.go:436 +0x27
created by os/exec.(*Cmd).Start
	c:/go/src/os/exec/exec.go:435 +0x608

goroutine 28174 [select]:
net/http.(*persistConn).writeLoop(0xc012e298c0)
	c:/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	c:/go/src/net/http/transport.go:1648 +0xc7b

goroutine 28395 [IO wait]:
internal/poll.runtime_pollWait(0x7fc1847e6538, 0x72, 0xffffffffffffffff)
	c:/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc015d92718, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	c:/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc015d92700, 0xc002b2e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc015d92700, 0xc002b2e000, 0x1000, 0x1000, 0x153ebc0, 0x72, 0x0)
	c:/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0092327d8, 0xc002b2e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:184 +0x8e
github.com/aliyun/aliyun-oss-go-sdk/oss.(*timeoutConn).Read(0xc016dd3ee0, 0xc002b2e000, 0x1000, 0x1000, 0x0, 0x0, 0x1)
	D:/workspace/golang/pkg/mod/github.com/aliyun/aliyun-oss-go-sdk@v2.1.0+incompatible/oss/conn.go:638 +0xa1
net/http.(*persistConn).Read(0xc012e28480, 0xc002b2e000, 0x1000, 0x1000, 0xc004dd4eb0, 0x4625d0, 0xc004dd4eb0)
	c:/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc015de4840)
	c:/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc015de4840, 0x1, 0x2, 0x0, 0x0, 0xc0148c8c00, 0x0)
	c:/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc012e28480)
	c:/go/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
	c:/go/src/net/http/transport.go:1647 +0xc56
```

**Comment by longshifeng** [comment]
@TruthHun 
I also met this problem. And how is it solved? Thanks!
